### PR TITLE
Mexican Spanish Translation

### PR DESCRIPTION
**Pull request by TheLegendofSaram**
So here is a Spanish Translation, There are several things in the mod that i could not translate cause they are not variables chagebles thru the lang file, maybe in the future they could be, but for now, this is the best I can do

### CODE REVIEW

**Comment by pufmat** [comment]
Thanks for contributing. I have seen your issue #80 and included translations in the mod. I should have replied to let you know that. Your translations haven't been released in a mod yet, because I'm currently working on a bigger update.

Before I merge this, please tell me what things are not in the language files, so I can add them.

**Comment by TheLegendofSaram** [comment]
Sure, I was not able to find this variables looking thru the mixin or other files, cause there is quite a bit of files and i dont really know how to do a mass search for varibles in a bunch of files so the next best thing is to show you
Captura de pantalla 2024-03-26 172518
Captura de pantalla 2024-03-26 172528

**As you can see, the two speech bubbles for the categories are one of these variables missing in the lang files**

Captura de pantalla 2024-03-26 172538
Captura de pantalla 2024-03-26 172624
Captura de pantalla 2024-03-26 172631

**And well, pretty much every skill upgrate bubble are also missing variables in the lang files** (I showed only the "melee damage" one in the combat category, but every single skill is in the same boat)

Hope this help, love your mod and sorry for not being able to pinpoint the exact files that carries these variables

**Comment by pufmat** [comment]
I decided to make not make the default skill tree translatable, as it is a part of the configuration. Because users can modify the skill tree, or use different one, so these translations in most cases would become invalid or unused. 

However, the update I'm currently working on is going to split the default skill tree into a separate data pack. Then I'm completely fine with translating it. But first I need to release that update.

Speaking of the update, one of the blocking issues are items in the GUI that become darker when using shaders. I could not reproduce it myself, but I have noticed on your screenshots, that you experience this issue. I would appreciate, if you could give me some details about used game version, mods, and shaders. You can also join my Discord server for easier communication.

**Comment by TheLegendofSaram** [comment]
Okkk, no problem I'll be waiting for update!! And Im not so sure if the darkness you refer to in the GUI are the skill boxes or the menu frame, if what you are refering to is the ladder, it is probably because of the resource pack [Default Dark Mode](https://modrinth.com/resourcepack/default-dark-mode), if not you can check my modlist [here](https://modrinth.com/modpack/soreass) is my personal modpack.
Ps: Sure I'll be joining your Discord :)

**Pull request merged**
